name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.18.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    # usecase_annotation:
    #     path: ../../usecase_annotation/
    usecase_annotation: ^0.0.5
    flutter_riverpod: ^1.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    build_runner: ^2.2.1
    usecase_generator:
        path: ../

flutter:
    uses-material-design: true
