name: usecase_annotation
description: usecase_annotation allows you to generate usecases class from the repository class
version: 0.0.5
homepage: https://github.com/dave20000/usecase.dart/tree/master/usecase_annotation

environment:
    sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
    test: ^1.21.6
    flutter_lints: ^2.0.0
